databases:
  - name: webrender_DB
    databaseName: webrender_db
    user: webrender
    region: singapore

services:
  - type: web
    name: webrender
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webrender_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
